### ISSUE TITLE
Error: Token is invalid

### ISSUE THREAD

**Issue by williamdwarke** [danielwarke/shopping-list#2]
Received this error after accepting invite and verifying account using a new email address:

![Screenshot 2024-05-20 122424](https://github.com/danielwarke/shopping-list/assets/20865387/e402881b-bea3-4727-b3f1-9a2ad2feb302)

Also, this error showed up in the console logs:
`{"statusCode":404,"message":"Cannot GET /auth/verify-email","error":"Not Found"}`

**Comment by williamdwarke** [comment]
Update: Login still works using new account

**Comment by danielwarke** [comment]
Woah wtf, why is it trying to GET that endpoint, that's a POST only 🤔 , let me look at that

**Comment by danielwarke** [comment]
The signup flow has been reworked and I don't think think will happen again 🙏🏻
