### ISSUE TITLE
Shared list doesn't show up after accepting invite

### ISSUE THREAD

**Issue by williamdwarke** [danielwarke/shopping-list#3]
When I accepted an email invite and created a new account, the list I tried to share originally doesn't show up on the new account.

**Comment by williamdwarke** [comment]
(Some of these might actually be feature requests bc I'm not 100% sure what the intended functionality is but this one seemed like a bug to me)

**Comment by danielwarke** [comment]
I've revamped the entire onboarding flow and the accepting list invite. This should be working now
